
torchatari:
  max_duration: 600
  inherits: _defaults
  definition: .
  install_variant: unpinned
  install_group: torch
  plan:
    method: per_gpu

  argv:
    --num-minibatches: 4
    --update-epochs: 4
    --num-steps: 128
    --num-envs: 8
    --total-timesteps: 1000000
    --env-id: Breakout-v5