version: 2.0
resnet50:
  observations:
  - {batch_size: 832, perf: 3323.87, cpu: 8, memory: 46121 MiB, torchmem: 35567 MiB, time: 1786198330, backend: 7.2.26015, flavor: rocm7.2, torch: 2.11.0}
resnet50-noio:
  observations:
  - {batch_size: 1408, perf: 4129.31, cpu: 8, memory: 152344 MiB, torchmem: 141340 MiB, time: 1786198921, backend: 7.2.26015, flavor: rocm7.2, torch: 2.11.0}
resnet152-ddp-gpus:
  observations:
  - {batch_size: 832, perf: 16317.19, cpu: 8, memory: 89094 MiB, torchmem: 72825 MiB, time: 1786199012, backend: 7.2.26015, flavor: rocm7.2, torch: 2.11.0}
convnext_large-fp32:
  observations:
  - {batch_size: 352, perf: 300.57, cpu: 8, memory: 143119 MiB, torchmem: 118269 MiB, time: 1786199101, backend: 7.2.26015, flavor: rocm7.2, torch: 2.11.0}
convnext_large-tf32:
  observations:
  - {batch_size: 344, perf: 301.08, cpu: 8, memory: 137856 MiB, torchmem: 115659 MiB, time: 1786199268, backend: 7.2.26015, flavor: rocm7.2, torch: 2.11.0}
convnext_large-tf32-fp16:
  observations:
  - {batch_size: 640, perf: 541.78, cpu: 8, memory: 155141 MiB, torchmem: 118863 MiB, time: 1786199385, backend: 7.2.26015, flavor: rocm7.2, torch: 2.11.0}
regnet_y_128gf:
  observations:
  - {batch_size: 128, perf: 286.42, cpu: 8, memory: 50906 MiB, torchmem: 43624 MiB, time: 1786199718, backend: 7.2.26015, flavor: rocm7.2, torch: 2.11.0}
bert-fp32:
  observations:
  - {batch_size: 256, perf: 308.19, cpu: 8, memory: 156907 MiB, torchmem: 141020 MiB, time: 1786199805, backend: 7.2.26015, flavor: rocm7.2, torch: 2.11.0}
bert-fp16:
  observations:
  - {batch_size: 376, perf: 1092.17, cpu: 8, memory: 166823 MiB, torchmem: 142645 MiB, time: 1786199859, backend: 7.2.26015, flavor: rocm7.2, torch: 2.11.0}
bert-tf32:
  observations:
  - {batch_size: 256, perf: 308.87, cpu: 8, memory: 156907 MiB, torchmem: 141020 MiB, time: 1786199946, backend: 7.2.26015, flavor: rocm7.2, torch: 2.11.0}
bert-tf32-fp16:
  observations:
  - {batch_size: 376, perf: 1096.69, cpu: 8, memory: 166823 MiB, torchmem: 142645 MiB, time: 1786200000, backend: 7.2.26015, flavor: rocm7.2, torch: 2.11.0}
t5:
  observations:
  - {batch_size: 72, perf: 227.67, cpu: 8, memory: 144643 MiB, torchmem: 130133 MiB, time: 1786200052, backend: 7.2.26015, flavor: rocm7.2, torch: 2.11.0}
reformer:
  observations:
  - {batch_size: 440, perf: 192.3, cpu: 8, memory: 166539 MiB, torchmem: 143752 MiB, time: 1786200242, backend: 7.2.26015, flavor: rocm7.2, torch: 2.11.0}
whisper:
  observations:
  - {batch_size: 1152, perf: 1626.37, cpu: 8, memory: 163217 MiB, torchmem: 140415 MiB, time: 1786200415, backend: 7.2.26015, flavor: rocm7.2, torch: 2.11.0}
focalnet:
  observations:
  - {batch_size: 1, perf: 9.7, cpu: 8, memory: 4802 MiB, time: 1786200618, backend: 7.2.26015, flavor: rocm7.2, torch: 2.11.0}
brax:
  observations:
  - {batch_size: 2048, perf: 1471454.77, cpu: 0, memory: 7195 MiB, jaxmem: 257 MiB, time: 1786200854, backend: 7.2.26015, flavor: rocm7.2, torch: 2.11.0}
diffusion-single:
  observations:
  - {batch_size: 104, perf: 87.18, cpu: 8, memory: 165032 MiB, torchmem: 137679 MiB, time: 1786201390, backend: 7.2.26015, flavor: rocm7.2, torch: 2.11.0}
diffusion-gpus:
  observations:
  - {batch_size: 96, perf: 664.36, cpu: 8, memory: 148795 MiB, torchmem: 131335 MiB, time: 1786201916, backend: 7.2.26015, flavor: rocm7.2, torch: 2.11.0}
lightning:
  observations:
  - {batch_size: 1568, perf: 2163.15, cpu: 8, memory: 160141 MiB, torchmem: 136344 MiB, time: 1786202332, backend: 7.2.26015, flavor: rocm7.2, torch: 2.11.0}
lightning-gpus:
  observations:
  - {batch_size: 512, perf: 15339.43, cpu: 8, memory: 83313 MiB, torchmem: 45828 MiB, time: 1786202434, backend: 7.2.26015, flavor: rocm7.2, torch: 2.11.0}
dinov2-giant-single:
  observations:
  - {batch_size: 128, perf: 217.42, cpu: 0, memory: 268154 MiB, torchmem: 208422 MiB, time: 1786202583, backend: 7.2.26015, flavor: rocm7.2, torch: 2.11.0}
dinov2-giant-gpus:
  observations:
  - {batch_size: 160, perf: 1550.87, cpu: 0, memory: 289242 MiB, torchmem: 244373 MiB, time: 1786202770, backend: 7.2.26015, flavor: rocm7.2, torch: 2.11.0}
llm-lora-ddp-gpus:
  observations:
  - {batch_size: 112, perf: 92026.14, cpu: 0, memory: 292993 MiB, torchmem: 130167 MiB, time: 1786204303, backend: 7.2.26015, flavor: rocm7.2, torch: 2.11.0}
llm-full-mp-gpus:
  observations:
  - {batch_size: 64, perf: 10701.29, cpu: 0, memory: 222395 MiB, torchmem: 122557 MiB, time: 1786205592, backend: 7.2.26015, flavor: rocm7.2, torch: 2.11.0}
dqn:
  observations:
  - {batch_size: 1, perf: 438095.76, cpu: 128, memory: 3701 MiB, jaxmem: 304 MiB, time: 1786205636, backend: 7.2.26015, flavor: rocm7.2, torch: 2.11.0}
pna:
  observations:
  - {batch_size: 20576, perf: 17277.13, cpu: 0, memory: 257615 MiB, torchmem: 133778 MiB, time: 1786205881, backend: 7.2.26015, flavor: rocm7.2, torch: 2.11.0}
dimenet:
  observations:
  - {batch_size: 2752, perf: 6747.81, cpu: 0, memory: 286679 MiB, torchmem: 138841 MiB, time: 1786205969, backend: 7.2.26015, flavor: rocm7.2, torch: 2.11.0}
recursiongfn:
  observations:
  - {batch_size: 192, perf: 11573.42, cpu: 8, memory: 47072 MiB, torchmem: 5424 MiB, time: 1786206127, backend: 7.2.26015, flavor: rocm7.2, torch: 2.11.0}
llava-single:
  observations:
  - {batch_size: 33, perf: 27.95, cpu: 4, memory: 283731 MiB, torchmem: 189523 MiB, time: 1786206251, backend: 7.2.26015, flavor: rocm7.2, torch: 2.11.0}
rlhf-single:
  observations:
  - {batch_size: 64, perf: 2256.77, cpu: 0, memory: 132321 MiB, torchmem: 33399 MiB, time: 1786206424, backend: 7.2.26015, flavor: rocm7.2, torch: 2.11.0}
rlhf-gpus:
  observations:
  - {batch_size: 288, perf: 9951.08, cpu: 0, memory: 273861 MiB, torchmem: 132890 MiB, time: 1786206582, backend: 7.2.26015, flavor: rocm7.2, torch: 2.11.0}
vjepa-single:
  observations:
  - {batch_size: 64, perf: 75.64, cpu: 12, memory: 144898 MiB, torchmem: 115005 MiB, time: 1786206771, backend: 7.2.26015, flavor: rocm7.2, torch: 2.11.0}
vjepa-gpus:
  observations:
  - {batch_size: 32, perf: 435.72, cpu: 12, memory: 92406 MiB, torchmem: 70391 MiB, time: 1786206985, backend: 7.2.26015, flavor: rocm7.2, torch: 2.11.0}
torchatari:
  observations:
  - {batch_size: 16, perf: 3958.03, cpu: 128, memory: 4574 MiB, torchmem: 2276 MiB, time: 1786207271, backend: 7.2.26015, flavor: rocm7.2, torch: 2.11.0}
txt-to-image-single:
  observations:
  - {batch_size: 192, perf: 69.47, cpu: 0, memory: 86923 MiB, torchmem: 67620 MiB, time: 1786212433, backend: 7.2.26015, flavor: rocm7.2, torch: 2.11.0}
llm-chat-completion:
  observations:
  - {batch_size: 40, perf: 34667.35, cpu: 0, memory: 24312 MiB, torchmem: 20437 MiB, time: 1786212477, backend: 7.2.26015, flavor: rocm7.2, torch: 2.11.0}
