FROM nvcr.io/nvidia/pytorch:26.02-py3

# Arguments
# ---------

# Use ofed_info -s to get your local version
ARG MOFED_VERSION=5.4-3.4.0.0
ARG CONFIG=all.yaml
ARG ARCH=cuda
ARG SELECT=""

ENV MILABENCH_GPU_ARCH=$ARCH
ENV MILABENCH_CONFIG_NAME=$CONFIG
ENV MILABENCH_DOCKER=1
ENV MILABENCH_SELECT=$SELECT
ENV TORCH_CUDA_ARCH_LIST="10.0;12.0;12.1"
ENV CUDA_HOME=/usr/local/cuda/

# Paths
# -----

ENV MILABENCH_CONFIG=/milabench/milabench/config/$MILABENCH_CONFIG_NAME
ENV MILABENCH_BASE=/milabench/results/
ENV MILABENCH_OUTPUT=/milabench/results/
ENV MILABENCH_ARGS=""

# Copy milabench
# --------------

WORKDIR /milabench
COPY . /milabench/milabench/


ENV DEBIAN_FRONTEND=noninteractive
ENV VIRTUAL_ENV=/milabench/env
ENV PATH="/milabench/env/bin:${PATH}"

# bash /milabench/milabench/docker/scripts/install.sh                 &&\

ENV I_CONFIRM_THIS_IS_NOT_A_LICENSE_VIOLATION=1

RUN cd $HOME                                                            &&\
    rm -rf /milabench/env                                               &&\
    pip install virtualenv                                              &&\
    virtualenv --system-site-packages /milabench/env                    &&\
    source /milabench/env/bin/activate                                  &&\
    /milabench/env/bin/pip install -e /milabench/milabench              &&\
    echo "torchcodec"                                                   &&\
    apt-get update                                                      &&\
    apt-get install -y pybind11-dev pkg-config ffmpeg libavdevice-dev libavfilter-dev libavformat-dev libavcodec-dev libavutil-dev libswresample-dev libswscale-dev &&\
    pip install "git+https://github.com/pytorch/torchcodec.git@release/0.7" --no-build-isolation           &&\
    milabench install --variant unpinned --use-current-env ${MILABENCH_SELECT:+--select $MILABENCH_SELECT}  &&\
    milabench prefer_system                                             &&\
    echo "torchao"                                                      &&\
    pip uninstall torchao                                               &&\
    pip install 'torchao<0.16.0' --no-build-isolation                   &&\
    /milabench/env/bin/pip cache purge




# pip install 'huggingface-hub<1.0'                                   &&\
# pip install https://github.com/vllm-project/vllm/releases/download/v0.17.1/vllm-0.17.1+cu130-cp38-abi3-manylinux_2_35_aarch64.whl &&\